import ReanderField from "./Field";
import { putData, deleteData, postData, getData } from "./axios";
import {
  LoadingApp,
  addWindowClass,
  generateSignature,
  getItem,
  removeItem,
  removeWindowClass,
  useWindowSize,
  setItem,
  validateEmail,
  renderStatus,
  maskPhoneNumber,
  formatNumber,
  getCurrentDateTime,
  maskEmail,
  pembulatan,
  calculateWindowSize,
  loadImage,
  LoadingContent,
  userData,
} from "./function";
export {
  putData,
  userData,
  deleteData,
  getData,
  postData,
  LoadingContent,
  loadImage,
  calculateWindowSize,
  renderStatus,
  pembulatan,
  formatNumber,
  getCurrentDateTime,
  maskEmail,
  maskPhoneNumber,
  validateEmail,
  getItem,
  removeItem,
  setItem,
  generateSignature,
  ReanderField,
  LoadingApp,
  addWindowClass,
  removeWindowClass,
  useWindowSize,
};
